# Generated by Django 2.2.6 on 2019-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191025_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('nature', 'Nature'), ('food', 'Food'), ('travel', 'Travel')], max_length=6),
        ),
    ]
