# Generated by Django 2.2.6 on 2019-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191029_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgfile',
            field=models.FileField(null=True, upload_to='static/images/', verbose_name=''),
        ),
    ]
