# Generated by Django 2.2.6 on 2019-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191029_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgfile',
            field=models.FileField(null=True, upload_to='media/images/', verbose_name=''),
        ),
    ]
