# Generated by Django 2.2.6 on 2019-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191029_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(default='', upload_to='media/images/'),
        ),
    ]
