# Generated by Django 2.2.6 on 2019-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191029_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
