# Generated by Django 2.2.6 on 2019-10-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191029_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('nature', 'Nature'), ('food', 'Food'), ('travel', 'Travel')], max_length=12),
        ),
    ]
