# Generated by Django 2.2.6 on 2019-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191030_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('nature', 'Nature'), ('world', 'world'), ('travel', 'Travel')], max_length=12),
        ),
    ]
